### ISSUE TITLE
Cannot run the code

### ISSUE THREAD

**Issue by paulbeomK** [IC3Net/IC3Net#14]
Hi, I'm sorry to trouble you,
I am trying to run the code in Traffic junction with the default setting with IC3Net and the others.
Except the others, only when run the IC3Net which is your proposed model, the following error is occur.
Traceback (most recent call last):
  File "/home/anaconda3/envs/ic3net/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/multi_processing.py", line 27, in run
    batch, stat = self.trainer.run_batch(epoch)
  File "/home/trainer.py", line 234, in run_batch
    episode, episode_stat = self.get_episode(epoch)
  File "/home//trainer.py", line 54, in get_episode
    action_out, value, prev_hid = self.policy_net(x, info)
  File "/home/envs/ic3net/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/IC3Net/comm.py", line 175, in forward
    agent_mask *= comm_action_mask.double()
RuntimeError: unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation 

I guess the hard_attention makes the problem, but not sure.
can you fix it or guide to run the IC3Net with default setting? Thanks.

**Comment by binz98** [comment]
Hi,I met the same problem, have you solved it？

**Comment by bkzfyx** [comment]
Refer to this page, https://stackoverflow.com/questions/59905234/runtimeerror-with-copy-and-expand-unsupported-operation-more-than-one-el ,add .clone() after expand() in comm.py can solve the problem

**Comment by ryndm** [comment]
Any update on this?

**Comment by MezereonXP** [comment]
You could try to modify the `comm.py` at 175 line:

```python
agent_mask = agent_mask * comm_action_mask.double()
```
